services:

  sonatype_nexus3:
    container_name: nexus3
    image: sonatype/nexus3
    ports:
      - "8081:8081"
    volumes:
      - nexus-data:/opt/nexus/data
    
    networks:
      - app_net


volumes:
  nexus-data:

networks:
  app_net:
    driver: bridge
